Repository ssu-it-project/cl-d-iOS, pull requests merged in 2023-11, with the labels that each got.

#75 [CHORE] UI 수정 사항 반영 (#74)
  CLD/Data/DTO+Mapping/Response/MyPage/UserHistoryDTO.swift
  CLD/Data/Network/_Foundation/LegacyNetwork/Service/RecordService.swift
  CLD/Presentation /Community/CommunityViewController.swift
  CLD/Presentation /MyPage/MyPageViewController.swift
  CLD/Presentation /MyPage/View/MyPageView.swift
  CLD/Presentation /Record/View/final/PostRecordViewController.swift
  CLD/Presentation /Record/View/final/SuccessRecordView.swift
  CLD/Presentation /Record/View/step4/SelectVideoViewController.swift
Labels: Chore 👍

#76 [CHORE] 암장 상세 기능 추가 & 홈 클라이밍 영상 피드 API 파싱 에러 해결 & 카카오톡 login 이슈 해결
  CLD.xcodeproj/project.pbxproj
  CLD.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  CLD/Data/DTO+Mapping/Response/ClimbingGym/BookmarkGymsDTO.swift
  CLD/Data/DTO+Mapping/Response/ClimbingGym/DetailGymDTO.swift
  CLD/Data/DTO+Mapping/Response/Record/RecordDTO.swift
  CLD/Data/DTO+Mapping/Response/Record/UserAlgorithmRecordDTO.swift
  CLD/Data/Network/API/GymsAPI.swift
  CLD/Data/Network/API/RecordAPI.swift
  CLD/Data/Network/_Foundation/URLConst.swift
  CLD/Data/Repository/ClimbingGym/DefaultGymsRepository.swift
  CLD/Data/Repository/Record/DefaultHomeRecordRepository.swift
  CLD/Domain/RepositoryInterface/ClimbingGym/GymsRepository.swift
  CLD/Domain/RepositoryInterface/Record/RecordRepository.swift
  CLD/Domain/Usecase/ClimbingGym/ClimbingGymDetailUseCase.swift
  CLD/Domain/Usecase/ClimbingGym/ClimbingGymUseCase.swift
  CLD/Domain/Usecase/ClimbingGym/ClimbingGymVideoUseCase.swift
  CLD/Domain/Usecase/Home/HomeRecordUseCase.swift
  CLD/Domain/VO/ClimbingGym/BookmarkGymsVO.swift
  CLD/Domain/VO/ClimbingGym/DetailGymVO.swift
  CLD/Domain/VO/Record/RecordVO.swift
  CLD/Domain/VO/Record/UserAlgorithmRecordVO.swift
  CLD/Presentation /CragSearch/View/Cell/ClimbingGymTableViewCell.swift
  CLD/Presentation /CragSearch/View/Cell/ClimbingGymVideoCollectionViewCell.swift
  CLD/Presentation /CragSearch/View/ClimbingGymDetailViewController.swift
  CLD/Presentation /CragSearch/View/ClimbingGymSearchViewController.swift
  CLD/Presentation /CragSearch/View/ClimbingGymVideoViewController.swift
  CLD/Presentation /CragSearch/ViewModel/ClimbingGymDetailViewModel.swift
  CLD/Presentation /CragSearch/ViewModel/ClimbingGymSearchViewModel.swift
  CLD/Presentation /Home/View/Cell/BadgeCollectionViewCell.swift
  CLD/Presentation /Home/View/HomeViewController.swift
  CLD/Presentation /Home/ViewModel/HomeViewModel.swift
  CLD/Presentation /Splash/SplashViewController.swift
Labels: Fix 🙏, Chore 👍

#78 [BUG] selectVideoVC 강제업래핑 제거 (#77)
  CLD/Presentation /Record/View/step4/SelectVideoViewController.swift
Labels: Fix 🙏
